### ISSUE TITLE
Stuck in infinite loop.  "Could not parse invalid json"

### ISSUE THREAD

**Issue by 0xStuart** [TransformerOptimus/SuperAGI#187] opened 2023-06-05 20:47 UTC
![image](https://github.com/TransformerOptimus/SuperAGI/assets/432831/5083c2ab-298a-42d4-80d3-70783e3cb542)

**Comment by maxrevilo** [comment] 2023-06-05 23:37
Yes, I've been having this issue for several kinds of tasks. The problem is using JSON to parse the agent's answers because even GPT4 isn't good at escaping strings for JSON fields.

So, in the meantime, you could add the following text at the end of the agent description:
```
Remember to escape the double quotes in the command string whenever you request a command, like creating a file. For example,
```"content": "{\n  "name": "discord-supabase-bot",\n  "version": "1.0.0",\n  "description": "A Discord bot that saves messages to Supabase"\n}"```
Is wrong. It should be
```"content": "{\"name\": \"discord-supabase-bot\",\"version\": \"1.0.0\",\"description\": \"A Discord bot that saves messages to Supabase\"}"```
Note how the external quotes are not escaped, only the quotes inside the string. Also, there are no newlines or spaces in the string representation of the JSON object.
```
It won't fix the issue, but it will reduce its occurrence.

**Comment by 6R15** [comment] 2023-06-06 12:08
![image](https://github.com/TransformerOptimus/SuperAGI/assets/126391930/4c7ac431-6c6a-4348-92a5-91b00fd3e790)

This is the method (check_and_clean_json from json_cleaner.py) where the json should be parsed and clean. 

And the issues happened here (output_parser.py): 
![image](https://github.com/TransformerOptimus/SuperAGI/assets/126391930/b2a32c95-1bea-408a-92c8-d480ce522d9d)

**Comment by aslaii** [comment] 2023-06-08 17:48
> > ![image](https://user-images.githubusercontent.com/126391930/243688375-4c7ac431-6c6a-4348-92a5-91b00fd3e790.png)
> > This is the method (check_and_clean_json from json_cleaner.py) where the json should be parsed and clean.
> > And the issues happened here (output_parser.py): ![image](https://user-images.githubusercontent.com/126391930/243688957-b2a32c95-1bea-408a-92c8-d480ce522d9d.png)
> 
> However, the real input is the llm model response.

Did you fix it?

**Comment by sharpie12** [comment] 2023-06-09 22:18
This seems to be one of the major issues I run into as well. I love this project and hope this issue isn't too difficult to address. It seems to happen the most when I ask it to code something, even a simple python script, (other then "hello world") can generate this error.

**Comment by 6R15** [comment] 2023-06-09 23:11
> This seems to be one of the major issues I run into as well. I love this project and hope this issue isn't too difficult to address. It seems to happen the most when I ask it to code something, even a simple python script, (other then "hello world") can generate this error.

It doesn't look that hard. AGI like auto-gpt also have a kind of method to fix json which works. I currently don't have enough time to really contribute. Maybe later :).

**Comment by brainshower** [comment] 2023-06-12 18:04
It's nearly unusable without this fixed.

**Comment by 6R15** [comment] 2023-06-14 08:13
Good news.  
![image](https://github.com/TransformerOptimus/SuperAGI/assets/126391930/667f7f85-33d0-4eb9-a42a-0c6c3b39dccb)
I will try it after my job done.

**Comment by neelayan7** [comment] 2023-06-27 11:34
We have fixed this issue. Thus closing this.

**Closed by neelayan7** 2023-06-27 11:34 UTC
