### ISSUE TITLE
FATAL:  password authentication failed for user "postgres" 

### ISSUE THREAD

**Issue by carlosbaraza** [TransformerOptimus/SuperAGI#368] opened 2023-06-14 10:02 UTC
v0.4.0 doesn't seem to work and throws this error when running:

```
superagi-super__postgres-1  | 2023-06-14 10:01:01.234 UTC [346] FATAL:  password authentication failed for user "postgres"
superagi-super__postgres-1  | 2023-06-14 10:01:01.234 UTC [346] DETAIL:  Role "postgres" does not exist.
```

**Comment by carlosbaraza** [comment] 2023-06-14 10:15
Solved it by changing the host port in the docker-compose.yml to different port:

```
ports:
      - "5435:5432"
```

I'm using OSX

**Comment by carlosbaraza** [comment] 2023-06-14 10:16
Refer to this for some ideas: https://github.com/sameersbn/docker-postgresql/issues/112

**Comment by neelayan7** [comment] 2023-06-15 07:47
Looks like the issue is resolved. Closing this.

**Closed by neelayan7** 2023-06-15 07:47 UTC
